name: Install ke server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy ke server
        uses: fifsky/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          command: |
            cd /var/www/html/release
            git pull origin master
            composer update 


    
      