name: Install ke server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deployToAWS:
    runs-on: ubuntu-latest 
    needs: build
    steps: 
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with: 
        token: ${{secrets.github_token}}  
    - name: Coba lihat version nya 
      run: echo "vesionnnya is $BUILD_NUMBER"
    - name: COnfigure AWS Cred 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-east-2
      
    - name: Copy files to the test website with the AWS CLI
      run: |
        /home/cloudshell-user/bin/auto.sh $BUILD_NUMBER

# AKIAYGVUCAHHW7EDJCMT

# QpApHcxkkHE+ZD2H6CZvqTdy9rgGln9gnIzLhpnR