name: Install ke server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy ke server
        uses: appleboy/ssh-action@v0.1.4
        with: 
          host: 165.22.105.141
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          # password: Rahasia1q2w3e4r
          port: 22
          script: |
            cd /var/www/html/release
            git pull
            composer  update --no-interaction
 
# i love this idea.. faaakk.. it's cool 