name: Install ke server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deployToAWS:
    runs-on: ubuntu-latest 
    #needs: build
    steps: 
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with: 
        token: ${{secrets.github_token}}  
    - name: Coba lihat version nya 
      run: echo "vesionnnya is $BUILD_NUMBER"
    - name: COnfigure AWS Cred 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-east-2
      
    - name: Copy files to the test website with the AWS CLI
      run: |
        VERSION=$BUILD_NUMBER
        NAME="ZONTOOL${VERSION}ZONTOOL"
        echo "NAMA $NAME"
        AMI=`aws ec2 create-image --instance-id i-011db2ec73bf07376 --name "$NAME" --no-reboot --output text`
        echo "ID AMI ${AMI}"
        echo "ami createed"
        NEW_LC="LCv${VERSION}"
        echo "create launch configuration"
        aws autoscaling create-launch-configuration  --launch-configuration-name "${NEW_LC}" --image-id ${AMI} --instance-type a1.medium
        echo "update autoscaling group"
        aws autoscaling update-auto-scaling-group --auto-scaling-group-name ZontoolAutoSG --launch-configuration-name "${NEW_LC}" 


# AKIAYGVUCAHHW7EDJCMT    s 

# QpApHcxkkHE+ZD2H6CZvqTdy9rgGln9gnIzLhpnR