name: Install ke server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy ke server
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: Rahasia1q2w3e4r
          port: 22
          script: |
            cd /var/www/html/release
            git pull origin master
            composer update 


    
      